### ISSUE TITLE
[Bug]: ReturnOutputData.__init__() got an unexpected keyword argument 'originalData'

### ISSUE THREAD

**Issue by maoLz** [SonnenladenGmbH/APsystems-EZ1-API#36]
### What happened?

Hello, I am going to use Home Assistant to integrate apsystem ez1, but the code reports an error. I checked the local interface return contains an extra parameter: "originalData". In your code, "__init__" failed.
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/1a4afe38-c041-4e36-a24d-3af4a7b86a62">

### The python error

```shell
2024-10-08 14:31:44.497 ERROR (MainThread) [homeassistant.components.apsystems] Unexpected error fetching APSystems Data data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/apsystems/coordinator.py", line 46, in _async_update_data
    output_data = await self.api.get_output_data()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/APsystemsEZ1/__init__.py", line 189, in get_output_data
    return ReturnOutputData(**response["data"]) if response else None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ReturnOutputData.__init__() got an unexpected keyword argument 'originalData'
```

### Your python version

python3

### Your OS inlcuding your version

Home ASSISTANT OS 13.1 (RPI 5)

**Comment by maoLz** [comment]
When I write the constructor manually, everything works fine. Can I submit a PR?

![image](https://github.com/user-attachments/assets/4da405f4-717d-407c-9c4e-a76362c8020a)

**Comment by mawoka-myblock** [comment]
That's not how it works, we'll have to investigate why your inverter returns that data, as other don't. Which model and firmware version are you using specifically?

**Comment by maoLz** [comment]
Thank you for your prompt reply, here is the photo of my inverter information:
![image](https://github.com/user-attachments/assets/6834bb2b-0578-4bdd-a97f-30f1395e0140)

**Comment by mawoka-myblock** [comment]
Very interesting! I'd appreciate a PR, but you have to make sure that the `originalData` is **optional** as my inverter doesn't return that. Just get started with the PR and feel free to ask for help there!

**Comment by maoLz** [comment]
Thank you, I have submitted a PR.
